# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# **Análisis de la Acción de Buenaventura**

```
**Contexto y Análisis de la Acción de BUENAVENTURA (US:** BVN)
Compañía de Minas Buenaventura S.A.A. es una empresa peruana, listada en la Bolsa de Valores de Nueva York (NYSE: BVN) y en la Bolsa de Valores de Lima (BVL). Es una de las compañías de metales preciosos más grandes del Perú, dedicada a la exploración, desarrollo y operación de minas de oro, plata, cobre, zinc y plomo. Buenaventura es reconocida por su compromiso con prácticas mineras sostenibles y su impacto en la economía peruana.

**Historia Resumida:**
Fundada en 1953, Buenaventura fue pionera en la minería moderna en el Perú. A lo largo de las décadas, ha crecido significativamente a través de la expansión de sus operaciones y la adquisición de nuevas propiedades. Ha sido un actor clave en el desarrollo de la infraestructura minera del país y ha participado en importantes joint ventures, como la mina Yanacocha (la mina de oro más grande de Sudamérica), donde es socia con Newmont. Su trayectoria se caracteriza por una constante búsqueda de eficiencia y nuevas reservas.

**Estadísticas del Sector Minero (Proyección 2026):**
El sector minero es un pilar fundamental de la economía peruana, representando una parte significativa del PIB, las exportaciones y la inversión extranjera. Para 2026, se espera que el sector continúe siendo un motor de crecimiento, impulsado por la demanda global de metales clave para la transición energética (cobre, zinc) y la estabilidad de los precios del oro y la plata. La producción de cobre y oro en Perú se proyecta que mantenga una posición destacada a nivel mundial.

Contribución al PIB de Perú: Se estima que la minería representará un X% del PIB nacional.
Exportaciones Mineras: Se prevé que las exportaciones de minerales alcancen los $Y mil millones, siendo el cobre y el oro los principales contribuyentes. - **Inversión en el sector:** La inversión en nuevos proyectos y expansión de operaciones se proyecta en $$Y mil millones, siendo el cobre y el oro los principales contribuyentes. - **Inversión en el sector:** La inversión en nuevos proyectos y expansión de operaciones se proyecta en $Z mil millones. (Nota: Las cifras X, Y, Z son placeholders y deberían ser actualizadas con datos económicos y proyecciones reales de 2026 cuando estén disponibles).
Estadísticas de la Acción de Buenaventura (Proyección 2026):
El rendimiento de la acción de Buenaventura estará influenciado por los precios de los metales, la producción de sus minas, los costos operativos y el entorno regulatorio *italicized text*.

Precio de la Acción (BVN): [Precio actual de la acción en 2026, por ejemplo, $XX.XX]
Capitalización de Mercado: [Valor de mercado de la empresa en 2026]
Volumen de Negociación Promedio: [Volumen promedio diario de acciones negociadas en 2026]
Dividendos: [Política de dividendos y pagos esperados en 2026]
Relación P/E: [Relación precio/ganancias en 2026] (Nota: Estos son placeholders. Para un análisis real, se necesitarían datos financieros y de mercado actualizados de Buenaventura para el año 2026). *italicized text*
```
"""

# ============================================================
# Análisis y gráficos de BVN vs Oro (GC=F)
# Solo evolución de precios, sin volumen
# Eje X formato mmm-yy + subgrilla semanal
# ============================================================

# Instalar librerías si estás en Google Colab
# !pip install yfinance mplfinance

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import mplfinance as mpf
from datetime import datetime, timedelta

# ============================================================
# 1. Configuración
# ============================================================

bvn_ticker = "BVN"
gold_ticker = "GC=F"

end_date = datetime.today()
start_date_1yr = end_date - timedelta(days=365)

# ============================================================
# 2. Función para preparar datos
# ============================================================

def preparar_data(data, ticker):
    print(f"\n--- Preparing data for {ticker} ---")

    if data.empty:
        print(f"No data downloaded for {ticker}.")
        return pd.DataFrame()

    if isinstance(data.columns, pd.MultiIndex):
        print(f"Flattening MultiIndex columns for {ticker}.")
        data.columns = data.columns.get_level_values(0)

    columnas_necesarias = ["Open", "High", "Low", "Close", "Volume"]

    for col in columnas_necesarias:
        if col not in data.columns:
            print(f"Falta la columna {col} para {ticker}.")
            return pd.DataFrame()

    data = data[columnas_necesarias].copy()

    for col in columnas_necesarias:
        data[col] = pd.to_numeric(data[col], errors="coerce")

    data = data.dropna()
    data = data[["Open", "High", "Low", "Close", "Volume"]]

    print(f"DataFrame for {ticker} prepared. Shape: {data.shape}")
    print(data.head())

    return data

# ============================================================
# 3. Función para formatear eje X
# ============================================================

def formatear_eje_x(ax):
    # Etiquetas principales: cada mes
    ax.xaxis.set_major_locator(mdates.MonthLocator())

    # Formato: Jun-25, Jul-25, Aug-25
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b-%y"))

    # Subgrilla: cada semana
    ax.xaxis.set_minor_locator(mdates.WeekdayLocator(interval=1))

    # Grilla mensual más visible
    ax.grid(
        True,
        which="major",
        axis="x",
        linestyle="-",
        linewidth=0.8,
        alpha=0.7
    )

    # Subgrilla semanal más suave
    ax.grid(
        True,
        which="minor",
        axis="x",
        linestyle=":",
        linewidth=0.5,
        alpha=0.5
    )

    # Grilla horizontal normal
    ax.grid(
        True,
        which="major",
        axis="y",
        linestyle="--",
        linewidth=0.5,
        alpha=0.5
    )

    # Rotar etiquetas
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right")

# ============================================================
# 4. Descargar datos de BVN
# ============================================================

print(f"Attempting to download data for {bvn_ticker}...")

bvn_data_1yr_raw = yf.download(
    bvn_ticker,
    start=start_date_1yr,
    end=end_date,
    progress=False,
    auto_adjust=True
)

bvn_data_1yr = preparar_data(bvn_data_1yr_raw, bvn_ticker)

# ============================================================
# 5. Descargar datos del oro
# ============================================================

print(f"\nAttempting to download data for {gold_ticker}...")

gold_data_1yr_raw = yf.download(
    gold_ticker,
    start=start_date_1yr,
    end=end_date,
    progress=False,
    auto_adjust=True
)

gold_data_1yr = preparar_data(gold_data_1yr_raw, gold_ticker)

# ============================================================
# 6. Gráfico de velas japonesas para BVN sin volumen
# ============================================================

if not bvn_data_1yr.empty:
    print(f"\nDEBUG: Plotting price data for {bvn_ticker}.")

    fig_bvn, axes_bvn = mpf.plot(
        bvn_data_1yr,
        type="candle",
        title=f"{bvn_ticker} - Evolución del Precio",
        ylabel="Precio",
        volume=False,
        style="yahoo",
        figsize=(14, 6),
        show_nontrading=True,
        returnfig=True
    )

    ax_bvn = axes_bvn[0]
    formatear_eje_x(ax_bvn)

    plt.show()

else:
    print(f"No hay datos disponibles para graficar {bvn_ticker}.")

# ============================================================
# 7. Gráfico de velas japonesas para Oro sin volumen
# ============================================================

if not gold_data_1yr.empty:
    print(f"\nDEBUG: Plotting price data for {gold_ticker}.")

    fig_gold, axes_gold = mpf.plot(
        gold_data_1yr,
        type="candle",
        title=f"{gold_ticker} - Evolución del Precio",
        ylabel="Precio",
        volume=False,
        style="yahoo",
        figsize=(14, 6),
        show_nontrading=True,
        returnfig=True
    )

    ax_gold = axes_gold[0]
    formatear_eje_x(ax_gold)

    plt.show()

else:
    print(f"No hay datos disponibles para graficar {gold_ticker}.")

# ============================================================
# 8. Gráfico comparativo normalizado BVN vs Oro
# ============================================================

if not bvn_data_1yr.empty and not gold_data_1yr.empty:

    comparativo = pd.DataFrame({
        "BVN": bvn_data_1yr["Close"],
        "Oro": gold_data_1yr["Close"]
    })

    comparativo = comparativo.dropna()

    comparativo_normalizado = comparativo / comparativo.iloc[0] * 100

    fig, ax = plt.subplots(figsize=(14, 6))

    ax.plot(
        comparativo_normalizado.index,
        comparativo_normalizado["BVN"],
        label="BVN"
    )

    ax.plot(
        comparativo_normalizado.index,
        comparativo_normalizado["Oro"],
        label="Oro GC=F"
    )

    ax.set_title("Comparativo Normalizado: BVN vs Oro")
    ax.set_xlabel("Fecha")
    ax.set_ylabel("Índice Base 100")
    ax.legend()

    # Aplicar mismo formato de eje X
    formatear_eje_x(ax)

    plt.tight_layout()
    plt.show()

# ============================================================
# 8. Correlación entre retornos diarios
# ============================================================

if not bvn_data_1yr.empty and not gold_data_1yr.empty:

    retornos = pd.DataFrame({
        "BVN": bvn_data_1yr["Close"].pct_change(),
        "Oro": gold_data_1yr["Close"].pct_change()
    })

    retornos = retornos.dropna()

    correlacion = retornos["BVN"].corr(retornos["Oro"])

    print("\n============================================================")
    print("Correlación de retornos diarios")
    print("============================================================")
    print(f"Correlación BVN vs Oro: {correlacion:.4f}")

# ============================================================
# 9. Rendimiento aproximado del último año
# ============================================================

if not bvn_data_1yr.empty and not gold_data_1yr.empty:

    rendimiento_bvn = (
        bvn_data_1yr["Close"].iloc[-1] / bvn_data_1yr["Close"].iloc[0] - 1
    ) * 100

    rendimiento_oro = (
        gold_data_1yr["Close"].iloc[-1] / gold_data_1yr["Close"].iloc[0] - 1
    ) * 100

    print("\n============================================================")
    print("Rendimiento aproximado último año")
    print("============================================================")
    print(f"BVN: {rendimiento_bvn:.2f}%")
    print(f"Oro GC=F: {rendimiento_oro:.2f}%")

"""# Correlación entre el Oro, la Plata y BVN..."""

silver_ticker = "SI=F"

print(f"\nAttempting to download data for {silver_ticker}...")
silver_data_1yr_raw = yf.download(
    silver_ticker,
    start=start_date_1yr,
    end=end_date,
    progress=False,
    auto_adjust=True
)
silver_data_1yr = preparar_data(silver_data_1yr_raw, silver_ticker)

if not bvn_data_1yr.empty and not gold_data_1yr.empty and not silver_data_1yr.empty:

    # Crear un DataFrame con los precios de cierre de los tres activos
    precios_comparacion = pd.DataFrame({
        "BVN": bvn_data_1yr["Close"],
        "Oro": gold_data_1yr["Close"],
        "Plata": silver_data_1yr["Close"]
    })

    # Eliminar cualquier fila con NaN (fechas sin datos para alguno de los activos)
    precios_comparacion = precios_comparacion.dropna()

    # Calcular los retornos diarios
    retornos_comparacion = precios_comparacion.pct_change().dropna()

    # Calcular la matriz de correlación
    matriz_correlacion = retornos_comparacion.corr()

    print("\n===========================================================")
    print("Matriz de Correlación de Retornos Diarios (BVN vs Oro vs Plata)")
    print("===========================================================")
    display(matriz_correlacion)
else:
    print("No hay datos suficientes para calcular la matriz de correlación de los tres activos.")

# ============================================================
# Evolución de la correlación BVN vs Oro en el último año
# Correlación móvil de retornos diarios
# ============================================================

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# ============================================================
# 1. Configuración
# ============================================================

bvn_ticker = "BVN"
gold_ticker = "GC=F"

end_date = datetime.today()
start_date_1yr = end_date - timedelta(days=365)

ventana_correlacion = 30  # días de ventana móvil

# ============================================================
# 2. Descargar datos
# ============================================================

bvn_data = yf.download(
    bvn_ticker,
    start=start_date_1yr,
    end=end_date,
    progress=False,
    auto_adjust=True
)

gold_data = yf.download(
    gold_ticker,
    start=start_date_1yr,
    end=end_date,
    progress=False,
    auto_adjust=True
)

# ============================================================
# 3. Preparar datos
# ============================================================

# Aplanar columnas si vienen como MultiIndex
if isinstance(bvn_data.columns, pd.MultiIndex):
    bvn_data.columns = bvn_data.columns.get_level_values(0)

if isinstance(gold_data.columns, pd.MultiIndex):
    gold_data.columns = gold_data.columns.get_level_values(0)

# Crear dataframe con precios de cierre
precios = pd.DataFrame({
    "BVN": bvn_data["Close"],
    "Oro": gold_data["Close"]
})

# Eliminar fechas incompletas
precios = precios.dropna()

# ============================================================
# 4. Calcular retornos diarios
# ============================================================

retornos = precios.pct_change().dropna()

# ============================================================
# 5. Calcular correlación móvil
# ============================================================

correlacion_movil = retornos["BVN"].rolling(
    window=ventana_correlacion
).corr(retornos["Oro"])

# ============================================================
# 6. Graficar evolución de la correlación
# ============================================================

plt.figure(figsize=(14, 6))

plt.plot(
    correlacion_movil.index,
    correlacion_movil,
    label=f"Correlación móvil {ventana_correlacion} días"
)

plt.axhline(0, linestyle="--", linewidth=1)
plt.axhline(1, linestyle="--", linewidth=0.8)
plt.axhline(-1, linestyle="--", linewidth=0.8)

plt.title("Evolución de la Correlación entre BVN y Oro")
plt.xlabel("Fecha")
plt.ylabel("Correlación")
plt.ylim(-1, 1)
plt.legend()
plt.grid(True)

plt.show()

# ============================================================
# 7. Mostrar último valor de correlación móvil
# ============================================================

ultimo_valor = correlacion_movil.dropna().iloc[-1]

print("============================================================")
print("Última correlación móvil calculada")
print("============================================================")
print(f"Ventana usada: {ventana_correlacion} días")
print(f"Última correlación móvil BVN vs Oro: {ultimo_valor:.4f}")

"""# **Hipótesis: BVN esta cayendo por toma de ganancias pero se mantiene en fundamentos solidos frente al Oro, ayudado por la correlación altamente positiva entre estos activos...**

---


"""

# ============================================================
# Análisis BVN vs Oro
# Hipótesis: caída de BVN por toma de ganancias,
# oro fuerte y correlación positiva BVN-Oro
# ============================================================

# En Google Colab, si falta alguna librería:
# !pip install yfinance mplfinance

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import mplfinance as mpf
from datetime import datetime, timedelta

# ============================================================
# 1. Configuración
# ============================================================

bvn_ticker = "BVN"
gold_ticker = "GC=F"

# Puedes cambiar años_analisis a 1, 2, 3 o 5
anios_analisis = 3

end_date = datetime.today()
start_date = end_date - timedelta(days=365 * anios_analisis)

# Ventanas
ventana_corr_1 = 30
ventana_corr_2 = 60
ventana_corr_3 = 90

# ============================================================
# 2. Funciones auxiliares
# ============================================================

def preparar_data(data, ticker):
    print(f"\n--- Preparing data for {ticker} ---")

    if data.empty:
        print(f"No data downloaded for {ticker}.")
        return pd.DataFrame()

    if isinstance(data.columns, pd.MultiIndex):
        print(f"Flattening MultiIndex columns for {ticker}.")
        data.columns = data.columns.get_level_values(0)

    columnas_necesarias = ["Open", "High", "Low", "Close", "Volume"]

    for col in columnas_necesarias:
        if col not in data.columns:
            print(f"Falta la columna {col} para {ticker}.")
            return pd.DataFrame()

    data = data[columnas_necesarias].copy()

    for col in columnas_necesarias:
        data[col] = pd.to_numeric(data[col], errors="coerce")

    data = data.dropna()
    data = data[["Open", "High", "Low", "Close", "Volume"]]

    print(f"DataFrame for {ticker} prepared. Shape: {data.shape}")
    print(data.head())

    return data


def formatear_eje_x(ax):
    ax.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b-%y"))
    ax.xaxis.set_minor_locator(mdates.WeekdayLocator(interval=1))

    ax.grid(True, which="major", axis="x", linestyle="-", linewidth=0.7, alpha=0.6)
    ax.grid(True, which="minor", axis="x", linestyle=":", linewidth=0.4, alpha=0.4)
    ax.grid(True, which="major", axis="y", linestyle="--", linewidth=0.5, alpha=0.5)

    plt.setp(ax.get_xticklabels(), rotation=45, ha="right")


def calcular_rsi(precios, ventana=14):
    delta = precios.diff()

    ganancias = delta.where(delta > 0, 0)
    perdidas = -delta.where(delta < 0, 0)

    promedio_ganancias = ganancias.rolling(window=ventana).mean()
    promedio_perdidas = perdidas.rolling(window=ventana).mean()

    rs = promedio_ganancias / promedio_perdidas
    rsi = 100 - (100 / (1 + rs))

    return rsi


def calcular_drawdown(precios):
    maximo_acumulado = precios.cummax()
    drawdown = precios / maximo_acumulado - 1
    return drawdown


# ============================================================
# 3. Descargar datos
# ============================================================

print(f"Attempting to download data for {bvn_ticker}...")

bvn_raw = yf.download(
    bvn_ticker,
    start=start_date,
    end=end_date,
    progress=False,
    auto_adjust=True
)

bvn_data = preparar_data(bvn_raw, bvn_ticker)

print(f"\nAttempting to download data for {gold_ticker}...")

gold_raw = yf.download(
    gold_ticker,
    start=start_date,
    end=end_date,
    progress=False,
    auto_adjust=True
)

gold_data = preparar_data(gold_raw, gold_ticker)

# ============================================================
# 4. Construir base de precios y retornos
# ============================================================

if bvn_data.empty or gold_data.empty:
    raise ValueError("No se pudo descargar data suficiente para BVN u Oro.")

precios = pd.DataFrame({
    "BVN": bvn_data["Close"],
    "Oro": gold_data["Close"]
})

precios = precios.dropna()

retornos = precios.pct_change().dropna()

# ============================================================
# 5. Gráfico 1: BVN vs Oro normalizado base 100
# ============================================================

precios_base100 = precios / precios.iloc[0] * 100

fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(precios_base100.index, precios_base100["BVN"], label="BVN")
ax.plot(precios_base100.index, precios_base100["Oro"], label="Oro GC=F")

ax.set_title("BVN vs Oro - Evolución Normalizada Base 100")
ax.set_xlabel("Fecha")
ax.set_ylabel("Índice Base 100")
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 6. Gráfico 2: Ratio relativo BVN / Oro
# ============================================================

ratio_bvn_oro = precios["BVN"] / precios["Oro"]
ratio_bvn_oro_base100 = ratio_bvn_oro / ratio_bvn_oro.iloc[0] * 100

fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(ratio_bvn_oro_base100.index, ratio_bvn_oro_base100)

ax.axhline(100, linestyle="--", linewidth=1)

ax.set_title("Ratio Relativo BVN / Oro - Base 100")
ax.set_xlabel("Fecha")
ax.set_ylabel("Ratio BVN/Oro Base 100")

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 7. Gráfico 3: Correlación móvil 30, 60 y 90 días
# ============================================================

corr_30 = retornos["BVN"].rolling(window=ventana_corr_1).corr(retornos["Oro"])
corr_60 = retornos["BVN"].rolling(window=ventana_corr_2).corr(retornos["Oro"])
corr_90 = retornos["BVN"].rolling(window=ventana_corr_3).corr(retornos["Oro"])

fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(corr_30.index, corr_30, label="Correlación 30 días")
ax.plot(corr_60.index, corr_60, label="Correlación 60 días")
ax.plot(corr_90.index, corr_90, label="Correlación 90 días")

ax.axhline(0, linestyle="--", linewidth=1)
ax.axhline(1, linestyle=":", linewidth=0.8)
ax.axhline(-1, linestyle=":", linewidth=0.8)

ax.set_title("Evolución de la Correlación Móvil BVN vs Oro")
ax.set_xlabel("Fecha")
ax.set_ylabel("Correlación")
ax.set_ylim(-1, 1)
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 8. Gráfico 4: Drawdown comparativo BVN vs Oro
# ============================================================

drawdown_bvn = calcular_drawdown(precios["BVN"])
drawdown_oro = calcular_drawdown(precios["Oro"])

fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(drawdown_bvn.index, drawdown_bvn * 100, label="BVN")
ax.plot(drawdown_oro.index, drawdown_oro * 100, label="Oro GC=F")

ax.axhline(0, linestyle="--", linewidth=1)

ax.set_title("Drawdown Comparativo BVN vs Oro")
ax.set_xlabel("Fecha")
ax.set_ylabel("Drawdown (%)")
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 9. Gráfico 5: BVN con medias móviles 20, 50 y 200
# ============================================================

bvn_tecnico = bvn_data.copy()

bvn_tecnico["MA20"] = bvn_tecnico["Close"].rolling(window=20).mean()
bvn_tecnico["MA50"] = bvn_tecnico["Close"].rolling(window=50).mean()
bvn_tecnico["MA200"] = bvn_tecnico["Close"].rolling(window=200).mean()

fig, ax = plt.subplots(figsize=(14, 6))

ax.plot(bvn_tecnico.index, bvn_tecnico["Close"], label="BVN Close")
ax.plot(bvn_tecnico.index, bvn_tecnico["MA20"], label="MA20")
ax.plot(bvn_tecnico.index, bvn_tecnico["MA50"], label="MA50")
ax.plot(bvn_tecnico.index, bvn_tecnico["MA200"], label="MA200")

ax.set_title("BVN - Precio con Medias Móviles 20, 50 y 200")
ax.set_xlabel("Fecha")
ax.set_ylabel("Precio")
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 10. Gráfico 6: Volumen de BVN
# ============================================================

fig, ax = plt.subplots(figsize=(14, 5))

ax.bar(bvn_data.index, bvn_data["Volume"])

ax.set_title("BVN - Evolución del Volumen")
ax.set_xlabel("Fecha")
ax.set_ylabel("Volumen")

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 11. Gráfico 7: RSI de BVN
# ============================================================

rsi_bvn = calcular_rsi(bvn_data["Close"], ventana=14)

fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(rsi_bvn.index, rsi_bvn, label="RSI 14")

ax.axhline(70, linestyle="--", linewidth=1, label="Sobrecompra 70")
ax.axhline(30, linestyle="--", linewidth=1, label="Sobreventa 30")
ax.axhline(50, linestyle=":", linewidth=1)

ax.set_title("BVN - RSI 14 días")
ax.set_xlabel("Fecha")
ax.set_ylabel("RSI")
ax.set_ylim(0, 100)
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 12. Gráfico 8: Scatter de retornos BVN vs Oro
# ============================================================

fig, ax = plt.subplots(figsize=(7, 6))

ax.scatter(retornos["Oro"], retornos["BVN"], alpha=0.6)

ax.axhline(0, linestyle="--", linewidth=1)
ax.axvline(0, linestyle="--", linewidth=1)

ax.set_title("Scatter de Retornos Diarios: BVN vs Oro")
ax.set_xlabel("Retorno Diario Oro")
ax.set_ylabel("Retorno Diario BVN")

plt.tight_layout()
plt.show()

# ============================================================
# 13. Regresión simple BVN vs Oro
# Retorno BVN = alpha + beta * Retorno Oro
# ============================================================

x = retornos["Oro"]
y = retornos["BVN"]

beta, alpha = np.polyfit(x, y, 1)

retorno_bvn_estimado = alpha + beta * x
residual_bvn = y - retorno_bvn_estimado

print("\n============================================================")
print("Regresión simple BVN vs Oro")
print("============================================================")
print(f"Alpha diario: {alpha:.6f}")
print(f"Beta BVN frente al Oro: {beta:.4f}")
print(f"Correlación total BVN vs Oro: {retornos['BVN'].corr(retornos['Oro']):.4f}")

# Scatter con línea de regresión
fig, ax = plt.subplots(figsize=(7, 6))

ax.scatter(x, y, alpha=0.6, label="Datos diarios")
ax.plot(x, retorno_bvn_estimado, label="Línea de regresión")

ax.axhline(0, linestyle="--", linewidth=1)
ax.axvline(0, linestyle="--", linewidth=1)

ax.set_title("Regresión de Retornos: BVN vs Oro")
ax.set_xlabel("Retorno Diario Oro")
ax.set_ylabel("Retorno Diario BVN")
ax.legend()

plt.tight_layout()
plt.show()

# ============================================================
# 14. Gráfico 9: Residual de BVN frente al Oro
# ============================================================

fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(residual_bvn.index, residual_bvn * 100)

ax.axhline(0, linestyle="--", linewidth=1)

ax.set_title("Residual Diario de BVN frente al Oro")
ax.set_xlabel("Fecha")
ax.set_ylabel("Residual (%)")

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 15. Residual acumulado reciente
# ============================================================

residual_acumulado = residual_bvn.cumsum()

fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(residual_acumulado.index, residual_acumulado * 100)

ax.axhline(0, linestyle="--", linewidth=1)

ax.set_title("Residual Acumulado de BVN frente al Oro")
ax.set_xlabel("Fecha")
ax.set_ylabel("Residual Acumulado (%)")

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 16. Resumen numérico final
# ============================================================

ultimo_precio_bvn = precios["BVN"].iloc[-1]
ultimo_precio_oro = precios["Oro"].iloc[-1]

rendimiento_bvn = (precios["BVN"].iloc[-1] / precios["BVN"].iloc[0] - 1) * 100
rendimiento_oro = (precios["Oro"].iloc[-1] / precios["Oro"].iloc[0] - 1) * 100

ultimo_drawdown_bvn = drawdown_bvn.iloc[-1] * 100
ultimo_drawdown_oro = drawdown_oro.iloc[-1] * 100

ultima_corr_30 = corr_30.dropna().iloc[-1]
ultima_corr_60 = corr_60.dropna().iloc[-1]
ultima_corr_90 = corr_90.dropna().iloc[-1]

ultimo_rsi = rsi_bvn.dropna().iloc[-1]

ultimo_residual = residual_bvn.iloc[-1] * 100
residual_acum_30d = residual_bvn.tail(30).sum() * 100

print("\n============================================================")
print("Resumen del análisis")
print("============================================================")
print(f"Periodo analizado: {anios_analisis} años")
print(f"Último precio BVN: {ultimo_precio_bvn:.2f}")
print(f"Último precio Oro GC=F: {ultimo_precio_oro:.2f}")
print("------------------------------------------------------------")
print(f"Rendimiento BVN periodo: {rendimiento_bvn:.2f}%")
print(f"Rendimiento Oro periodo: {rendimiento_oro:.2f}%")
print("------------------------------------------------------------")
print(f"Drawdown actual BVN: {ultimo_drawdown_bvn:.2f}%")
print(f"Drawdown actual Oro: {ultimo_drawdown_oro:.2f}%")
print("------------------------------------------------------------")
print(f"Correlación móvil 30 días: {ultima_corr_30:.4f}")
print(f"Correlación móvil 60 días: {ultima_corr_60:.4f}")
print(f"Correlación móvil 90 días: {ultima_corr_90:.4f}")
print("------------------------------------------------------------")
print(f"RSI BVN 14 días: {ultimo_rsi:.2f}")
print(f"Beta BVN frente al Oro: {beta:.4f}")
print("------------------------------------------------------------")
print(f"Último residual diario BVN vs Oro: {ultimo_residual:.2f}%")
print(f"Residual acumulado últimos 30 días: {residual_acum_30d:.2f}%")

# ============================================================
# 17. Lectura automática simple
# ============================================================

print("\n================================================------------")
print("Lectura automática preliminar")
print("================================================------------")

if ultima_corr_60 > 0:
    print("La correlación móvil de 60 días es positiva: BVN mantiene relación positiva con el oro.")
else:
    print("La correlación móvil de 60 días no es positiva: la relación reciente BVN-Oro está débil o rota.")

if ultimo_drawdown_bvn > ultimo_drawdown_oro:
    print("BVN tiene menor drawdown que el oro.")
else:
    print("BVN tiene mayor drawdown que el oro.")

if ultimo_rsi < 70 and ultimo_rsi > 30:
    print("El RSI está en zona neutral: no hay señal extrema de sobrecompra o sobreventa.")
elif ultimo_rsi >= 70:
    print("El RSI está en zona de sobrecompra: puede existir riesgo de toma de ganancias.")
else:
    print("El RSI está en zona de sobreventa: la caída podría estar avanzada técnicamente.")

if residual_acum_30d < 0:
    print("El residual acumulado de 30 días es negativo: BVN rindió peor que lo explicado solo por el oro.")
else:
    print("El residual acumulado de 30 días es positivo: BVN rindió mejor que lo explicado solo por el oro.")

print("============================================================")

"""# **Conclusión Preliminar:**
++++++++++++++++++++++++++++++++++++
La evidencia técnica favorece una interpretación de corrección o toma de ganancias en BVN, más que una ruptura estructural de la relación con el oro. BVN ha tenido un rendimiento acumulado muy superior al oro en los últimos 3 años, mantiene correlaciones móviles positivas alrededor de 0.60, tiene beta positivo mayor a 1 y el residual acumulado de 30 días sigue siendo positivo. Sin embargo, el último residual diario negativo y el drawdown ligeramente mayor de BVN sugieren que conviene revisar si hubo una noticia puntual, presión de volumen o evento corporativo reciente.

# ## Análisis Complementario: Descomposición Sectorial y Relativa de BVN

En esta sección se amplía el análisis de BVN frente al oro incorporando benchmarks sectoriales. El objetivo es distinguir si la corrección reciente de BVN responde a una toma de ganancias específica de la acción, a una corrección general del sector de mineras de oro/plata, o a un desacople respecto del precio del oro.

Para ello se compara BVN contra cuatro referencias: oro futuro (GC=F), GDX como proxy de mineras auríferas grandes, GDXJ como proxy de mineras junior y SIL como proxy de mineras de plata. Se analizan rendimientos normalizados, ratios relativos, drawdowns, correlaciones móviles, betas y residuales acumulados.

*¿La caída de BVN responde a una toma de ganancias propia, a una corrección general del sector minero aurífero, o a un desacople específico frente al oro?*
"""

# ============================================================
# 10. Análisis Complementario:
# Descomposición Sectorial y Relativa de BVN
# ============================================================
#
# Objetivo:
# Evaluar si la caída de BVN es específica de la acción,
# parte de una corrección general de mineras,
# o una toma de ganancias relativa frente al oro.
#
# Activos:
# BVN   = Buenaventura
# GC=F  = Oro futuro
# GDX   = ETF de mineras de oro grandes
# GDXJ  = ETF de mineras de oro junior
# SIL   = ETF de mineras de plata
#
# ============================================================

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta

# ============================================================
# 1. Configuración del análisis complementario
# ============================================================

tickers_complementarios = {
    "BVN": "BVN",
    "Oro": "GC=F",
    "GDX": "GDX",
    "GDXJ": "GDXJ",
    "SIL": "SIL"
}

anios_analisis = 3

end_date = datetime.today()
start_date = end_date - timedelta(days=365 * anios_analisis)

# ============================================================
# 2. Funciones auxiliares
# ============================================================

def formatear_eje_x(ax):
    ax.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b-%y"))
    ax.xaxis.set_minor_locator(mdates.WeekdayLocator(interval=1))

    ax.grid(True, which="major", axis="x", linestyle="-", linewidth=0.7, alpha=0.6)
    ax.grid(True, which="minor", axis="x", linestyle=":", linewidth=0.4, alpha=0.4)
    ax.grid(True, which="major", axis="y", linestyle="--", linewidth=0.5, alpha=0.5)

    plt.setp(ax.get_xticklabels(), rotation=45, ha="right")


def descargar_close(ticker):
    data = yf.download(
        ticker,
        start=start_date,
        end=end_date,
        progress=False,
        auto_adjust=True
    )

    if data.empty:
        print(f"No se pudo descargar data para {ticker}.")
        return pd.Series(dtype=float)

    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.get_level_values(0)

    close = pd.to_numeric(data["Close"], errors="coerce")
    close = close.dropna()

    return close


def calcular_drawdown(precios):
    return precios / precios.cummax() - 1


# ============================================================
# 3. Descargar precios de cierre
# ============================================================

precios_comp = pd.DataFrame()

for nombre, ticker in tickers_complementarios.items():
    print(f"Descargando {nombre} ({ticker})...")
    precios_comp[nombre] = descargar_close(ticker)

precios_comp = precios_comp.dropna()

print("\nPrecios descargados:")
print(precios_comp.head())
print("\nShape:")
print(precios_comp.shape)

# ============================================================
# 4. Retornos diarios
# ============================================================

retornos_comp = precios_comp.pct_change().dropna()

# ============================================================
# 5. Gráfico 1:
# Evolución normalizada Base 100
# BVN vs Oro vs GDX vs GDXJ vs SIL
# ============================================================

precios_comp_base100 = precios_comp / precios_comp.iloc[0] * 100

fig, ax = plt.subplots(figsize=(14, 6))

for columna in precios_comp_base100.columns:
    ax.plot(
        precios_comp_base100.index,
        precios_comp_base100[columna],
        label=columna
    )

ax.set_title("Evolución Normalizada Base 100: BVN vs Oro, GDX, GDXJ y SIL")
ax.set_xlabel("Fecha")
ax.set_ylabel("Índice Base 100")
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 6. Gráfico 2:
# Ratios relativos de BVN frente a cada benchmark
# ============================================================

ratio_bvn_oro = precios_comp["BVN"] / precios_comp["Oro"]
ratio_bvn_gdx = precios_comp["BVN"] / precios_comp["GDX"]
ratio_bvn_gdxj = precios_comp["BVN"] / precios_comp["GDXJ"]
ratio_bvn_sil = precios_comp["BVN"] / precios_comp["SIL"]

ratios = pd.DataFrame({
    "BVN/Oro": ratio_bvn_oro,
    "BVN/GDX": ratio_bvn_gdx,
    "BVN/GDXJ": ratio_bvn_gdxj,
    "BVN/SIL": ratio_bvn_sil
})

ratios_base100 = ratios / ratios.iloc[0] * 100

fig, ax = plt.subplots(figsize=(14, 6))

for columna in ratios_base100.columns:
    ax.plot(
        ratios_base100.index,
        ratios_base100[columna],
        label=columna
    )

ax.axhline(100, linestyle="--", linewidth=1)

ax.set_title("Ratios Relativos de BVN frente a Oro, GDX, GDXJ y SIL - Base 100")
ax.set_xlabel("Fecha")
ax.set_ylabel("Ratio Base 100")
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 7. Gráfico 3:
# Drawdown comparativo
# ============================================================

drawdowns_comp = precios_comp.apply(calcular_drawdown) * 100

fig, ax = plt.subplots(figsize=(14, 6))

for columna in drawdowns_comp.columns:
    ax.plot(
        drawdowns_comp.index,
        drawdowns_comp[columna],
        label=columna
    )

ax.axhline(0, linestyle="--", linewidth=1)

ax.set_title("Drawdown Comparativo: BVN vs Oro, GDX, GDXJ y SIL")
ax.set_xlabel("Fecha")
ax.set_ylabel("Drawdown (%)")
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 8. Gráfico 4:
# Correlación móvil de BVN con cada benchmark
# ============================================================

ventana_corr = 60

corr_bvn_oro = retornos_comp["BVN"].rolling(ventana_corr).corr(retornos_comp["Oro"])
corr_bvn_gdx = retornos_comp["BVN"].rolling(ventana_corr).corr(retornos_comp["GDX"])
corr_bvn_gdxj = retornos_comp["BVN"].rolling(ventana_corr).corr(retornos_comp["GDXJ"])
corr_bvn_sil = retornos_comp["BVN"].rolling(ventana_corr).corr(retornos_comp["SIL"])

corr_comp = pd.DataFrame({
    "BVN-Oro": corr_bvn_oro,
    "BVN-GDX": corr_bvn_gdx,
    "BVN-GDXJ": corr_bvn_gdxj,
    "BVN-SIL": corr_bvn_sil
})

fig, ax = plt.subplots(figsize=(14, 6))

for columna in corr_comp.columns:
    ax.plot(
        corr_comp.index,
        corr_comp[columna],
        label=columna
    )

ax.axhline(0, linestyle="--", linewidth=1)
ax.axhline(1, linestyle=":", linewidth=0.8)
ax.axhline(-1, linestyle=":", linewidth=0.8)

ax.set_title(f"Correlación Móvil {ventana_corr} días: BVN vs Benchmarks")
ax.set_xlabel("Fecha")
ax.set_ylabel("Correlación")
ax.set_ylim(-1, 1)
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 9. Gráfico 5:
# Performance acumulado reciente: últimos 30, 60 y 90 días
# ============================================================

horizontes = [30, 60, 90]

for h in horizontes:
    if len(precios_comp) > h:
        precios_recientes = precios_comp.tail(h)
        base100_reciente = precios_recientes / precios_recientes.iloc[0] * 100

        fig, ax = plt.subplots(figsize=(14, 6))

        for columna in base100_reciente.columns:
            ax.plot(
                base100_reciente.index,
                base100_reciente[columna],
                label=columna
            )

        ax.set_title(f"Performance Normalizado Últimos {h} Días: BVN vs Benchmarks")
        ax.set_xlabel("Fecha")
        ax.set_ylabel("Índice Base 100")
        ax.legend()

        formatear_eje_x(ax)
        plt.tight_layout()
        plt.show()

# ============================================================
# 10. Tabla de rendimiento por horizonte
# ============================================================

horizontes_tabla = [5, 20, 30, 60, 90, 180, 252]

rendimientos = {}

for h in horizontes_tabla:
    if len(precios_comp) > h:
        rendimientos[f"{h} días"] = (
            precios_comp.iloc[-1] / precios_comp.iloc[-h] - 1
        ) * 100

tabla_rendimientos = pd.DataFrame(rendimientos).T

print("\n============================================================")
print("Rendimientos por Horizonte (%)")
print("============================================================")
print(tabla_rendimientos.round(2))

# ============================================================
# 11. Tabla de drawdown actual
# ============================================================

drawdown_actual = drawdowns_comp.iloc[-1].sort_values()

print("\n============================================================")
print("Drawdown Actual (%)")
print("============================================================")
print(drawdown_actual.round(2))

# ============================================================
# 12. Tabla de correlaciones recientes
# ============================================================

correlaciones_actuales = corr_comp.iloc[-1].sort_values(ascending=False)

print("\n============================================================")
print(f"Correlaciones Móviles Actuales - {ventana_corr} días")
print("============================================================")
print(correlaciones_actuales.round(4))

# ============================================================
# 13. Regresión BVN contra GDX y GDXJ
# ============================================================
#
# Esto ayuda a saber si BVN se comporta más como una minera
# que como una exposición directa al oro.
#
# Modelo:
# Retorno BVN = alpha + beta * retorno benchmark
#
# ============================================================

benchmarks_regresion = ["Oro", "GDX", "GDXJ", "SIL"]

resultados_regresion = []

for benchmark in benchmarks_regresion:
    x = retornos_comp[benchmark]
    y = retornos_comp["BVN"]

    beta, alpha = np.polyfit(x, y, 1)

    y_estimado = alpha + beta * x
    residual = y - y_estimado

    correlacion = y.corr(x)
    residual_30d = residual.tail(30).sum() * 100

    resultados_regresion.append({
        "Benchmark": benchmark,
        "Alpha diario": alpha,
        "Beta": beta,
        "Correlación": correlacion,
        "Residual acumulado 30d (%)": residual_30d
    })

tabla_regresion = pd.DataFrame(resultados_regresion)

print("\n============================================================")
print("Regresión de BVN frente a Benchmarks")
print("============================================================")
print(tabla_regresion.round(4))

# ============================================================
# 14. Residuales acumulados de BVN frente a cada benchmark
# ============================================================

residuales_acumulados = pd.DataFrame(index=retornos_comp.index)

for benchmark in benchmarks_regresion:
    x = retornos_comp[benchmark]
    y = retornos_comp["BVN"]

    beta, alpha = np.polyfit(x, y, 1)
    y_estimado = alpha + beta * x
    residual = y - y_estimado

    residuales_acumulados[f"Residual vs {benchmark}"] = residual.cumsum() * 100

fig, ax = plt.subplots(figsize=(14, 6))

for columna in residuales_acumulados.columns:
    ax.plot(
        residuales_acumulados.index,
        residuales_acumulados[columna],
        label=columna
    )

ax.axhline(0, linestyle="--", linewidth=1)

ax.set_title("Residual Acumulado de BVN frente a Oro, GDX, GDXJ y SIL")
ax.set_xlabel("Fecha")
ax.set_ylabel("Residual Acumulado (%)")
ax.legend()

formatear_eje_x(ax)
plt.tight_layout()
plt.show()

# ============================================================
# 15. Lectura automática complementaria
# ============================================================

print("\n============================================================")
print("Lectura automática complementaria")
print("============================================================")

# Rendimiento últimos 30 días
if "30 días" in tabla_rendimientos.index:
    r30 = tabla_rendimientos.loc["30 días"].sort_values(ascending=False)

    print("\nRendimiento últimos 30 días, de mayor a menor:")
    print(r30.round(2))

    bvn_30 = tabla_rendimientos.loc["30 días", "BVN"]
    gdx_30 = tabla_rendimientos.loc["30 días", "GDX"]
    gdxj_30 = tabla_rendimientos.loc["30 días", "GDXJ"]
    oro_30 = tabla_rendimientos.loc["30 días", "Oro"]

    print("\nInterpretación 30 días:")

    if bvn_30 < gdx_30 and bvn_30 < gdxj_30:
        print("BVN rindió peor que GDX y GDXJ: puede haber presión específica sobre BVN.")
    elif bvn_30 < oro_30 and gdx_30 < oro_30 and gdxj_30 < oro_30:
        print("Las mineras rindieron peor que el oro: la presión parece sectorial, no solo específica de BVN.")
    elif bvn_30 > gdx_30 and bvn_30 > gdxj_30:
        print("BVN rindió mejor que los ETFs mineros: la caída no parece ser presión relativa severa sobre BVN.")
    else:
        print("La señal es mixta: conviene revisar volumen, noticias y residuales.")

print("\nDrawdown actual, de peor a mejor:")
print(drawdown_actual.round(2))

print("\nCorrelaciones móviles actuales:")
print(correlaciones_actuales.round(4))

print("\nConclusión orientativa:")
print("Si BVN cae junto con GDX/GDXJ, la corrección parece sectorial.")
print("Si BVN cae más que GDX/GDXJ, puede existir factor propio o toma de ganancias específica.")
print("Si BVN cae pero el residual acumulado frente a GDX/GDXJ sigue positivo, la acción aún no muestra deterioro relativo fuerte.")
print("============================================================")

